version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    registries:
      - npm-codeartifact
    open-pull-requests-limit: 10

registries:
  npm-codeartifact:
    type: npm-registry
    url: https://registry-prod-904690835784.d.codeartifact.eu-west-2.amazonaws.com/npm/registry-prod-repo/
    aws-region: eu-west-2
    account-id: '904690835784'
    role-name: {{ secrets.AWS_ROLE_NAME }}
    domain: registry-prod
    domain-owner: '904690835784'
